from myapp.views.admin.thing import *
from myapp.views.admin.classification import *
from myapp.views.admin.user import *
from myapp.views.admin.loginLog import *
from myapp.views.admin.opLog import *
from myapp.views.admin.errorLog import *
from myapp.views.admin.courseinfo import *
from myapp.views.admin.score import *
from myapp.views.admin.active import *
